// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sreLIbL4oNr4CYoCz0WsCXHOejmZ1b8',
    appId: '1:18949852453:web:96aa6ac928af94543d1ecc',
    messagingSenderId: '18949852453',
    projectId: 'ies-67563',
    authDomain: 'ies-67563.firebaseapp.com',
    storageBucket: 'ies-67563.appspot.com',
    measurementId: 'G-CRKRPVG5XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGpvoeJnMOTXJVUrgiivICCcN_Bg0cYA',
    appId: '1:18949852453:android:50a34e05b088643c3d1ecc',
    messagingSenderId: '18949852453',
    projectId: 'ies-67563',
    storageBucket: 'ies-67563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8wW2NHcXDqbrGUL49AbNwLVOyvKXoZ6M',
    appId: '1:18949852453:ios:97647911d2d0ef8e3d1ecc',
    messagingSenderId: '18949852453',
    projectId: 'ies-67563',
    storageBucket: 'ies-67563.appspot.com',
    iosClientId: '18949852453-j12hd3qfsv3ku43nekma3n2ijv3e0srs.apps.googleusercontent.com',
    iosBundleId: 'com.example.iesFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8wW2NHcXDqbrGUL49AbNwLVOyvKXoZ6M',
    appId: '1:18949852453:ios:97647911d2d0ef8e3d1ecc',
    messagingSenderId: '18949852453',
    projectId: 'ies-67563',
    storageBucket: 'ies-67563.appspot.com',
    iosClientId: '18949852453-j12hd3qfsv3ku43nekma3n2ijv3e0srs.apps.googleusercontent.com',
    iosBundleId: 'com.example.iesFlutterApplication',
  );
}
